<a href="https://colab.research.google.com/github/MFarisA/Data-Mining/blob/main/data_mining_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/campuss/data-mining/dataKasus-1.xlsx'


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Load Dataset

In [88]:
import pandas as pd
from IPython.display import display

# Load Excel file
df = pd.read_excel('/content/drive/MyDrive/campuss/data-mining/dataKasus-1.xlsx')

# Check the first few rows
display(df.head())
# Display the column names (without calling it as a function)
display(df.columns)

NO    NAMA   USIA  PARITAS JARAK KELAHIRAN RIW HIPERTENSI RIW PE OBESITAS  \
0   1  NAMA 1  23 TH        3       < 2 tahun          Tidak  Tidak    Tidak   
1   2  NAMA 2  29 TH        2       < 2 tahun          Tidak    PEB    Tidak   
2   3  NAMA 3  20 TH        1    anak pertama          Tidak  Tidak    Tidak   
3   4  NAMA 4  18 TH        1    anak pertama          Tidak  Tidak    Tidak   
4   5  NAMA 5  34 TH        3      > 2 tahun           Tidak  Tidak    Tidak   

  RIW DM RIW HIPERTENSI/PE DALAM KELUARGA SOSEK RENDAH PE/Non PE Unnamed: 12  
0     Ya                            Tidak         >UMR    Non PE         NaN  
1  Tidak                              Ada         >UMR        PE         NaN  
2  Tidak                            Tidak         >UMR    Non PE         NaN  
3  Tidak                            Tidak         >UMR    Non PE         NaN  
4  Tidak                            Tidak         >UMR    Non PE         NaN

Index(['NO', 'NAMA', 'USIA', 'PARITAS', 'JARAK KELAHIRAN', 'RIW HIPERTENSI',
       'RIW PE', 'OBESITAS', 'RIW DM', 'RIW HIPERTENSI/PE DALAM KELUARGA',
       'SOSEK RENDAH', 'PE/Non PE', 'Unnamed: 12'],
      dtype='object')

## Handle missing Data


In [89]:
# Drop rows with any missing values
data_clean = df.dropna()

# Drop columns with missing values
data_clean = df.dropna(axis=1)

In [90]:
# Check for missing values in each column
print(df.isnull().sum())

NO                                    0
NAMA                                  0
USIA                                  3
PARITAS                               0
JARAK KELAHIRAN                       7
RIW HIPERTENSI                        0
RIW PE                                0
OBESITAS                              0
RIW DM                                0
RIW HIPERTENSI/PE DALAM KELUARGA      0
SOSEK RENDAH                          0
PE/Non PE                             0
Unnamed: 12                         550
dtype: int64


In [91]:
# Check if there are any missing values in the entire DataFrame
print(df.isnull().values.any())

True


In [92]:
# Calculate the percentage of missing values in each column
missing_percentage = df.isnull().mean() * 100
print(missing_percentage)

NO                                   0.000000
NAMA                                 0.000000
USIA                                 0.534759
PARITAS                              0.000000
JARAK KELAHIRAN                      1.247772
RIW HIPERTENSI                       0.000000
RIW PE                               0.000000
OBESITAS                             0.000000
RIW DM                               0.000000
RIW HIPERTENSI/PE DALAM KELUARGA     0.000000
SOSEK RENDAH                         0.000000
PE/Non PE                            0.000000
Unnamed: 12                         98.039216
dtype: float64


## Label Encoding, Normalization


In [93]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Initialize label encoder and scaler
le = LabelEncoder()
scaler = MinMaxScaler()

# Apply label encoding to each column
df['OBESITAS'] = le.fit_transform(df['OBESITAS'])
df['RIW HIPERTENSI'] = le.fit_transform(df['RIW HIPERTENSI'])
df['SOSEK RENDAH'] = le.fit_transform(df['SOSEK RENDAH'])

# Normalize the encoded data (scales between 0 and 1)
df[['OBESITAS', 'RIW HIPERTENSI', 'SOSEK RENDAH']] = scaler.fit_transform(df[['OBESITAS', 'RIW HIPERTENSI', 'SOSEK RENDAH']])

# Compare with other columns (e.g., 'NAMA', 'USIA', etc.)
print(df[['NAMA', 'USIA', 'JARAK KELAHIRAN', 'OBESITAS', 'RIW HIPERTENSI', 'SOSEK RENDAH']].head(10))


      NAMA   USIA JARAK KELAHIRAN  OBESITAS  RIW HIPERTENSI  SOSEK RENDAH
0   NAMA 1  23 TH       < 2 tahun       0.0             0.0           1.0
1   NAMA 2  29 TH       < 2 tahun       0.0             0.0           1.0
2   NAMA 3  20 TH    anak pertama       0.0             0.0           1.0
3   NAMA 4  18 TH    anak pertama       0.0             0.0           1.0
4   NAMA 5  34 TH      > 2 tahun        0.0             0.0           1.0
5   NAMA 6  28 TH       < 2 tahun       0.0             0.0           1.0
6   NAMA 7  36 TH      > 2 tahun        0.0             0.0           1.0
7   NAMA 8  28 TH      > 2 tahun        0.0             0.0           1.0
8   NAMA 9  39 TH       < 2 tahun       0.0             0.0           1.0
9  NAMA 10  37 TH      > 2 tahun        0.0             0.0           1.0


## Remove Duplicates

In [94]:
data_clean = df.drop_duplicates()

## Handle Outliers, Feature Engineering

In [95]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load your data
df = pd.read_excel('/content/drive/MyDrive/campuss/data-mining/dataKasus-1.xlsx')

# Convert 'OBESITAS', 'RIW HIPERTENSI', and 'SOSEK RENDAH' to numeric, handling errors
for col in ['OBESITAS', 'RIW HIPERTENSI', 'SOSEK RENDAH']:
    df[col] = pd.to_numeric(df[col], errors='coerce')  # 'coerce' will replace non-numeric values with NaN

# Specify the features and target variable
# Assuming 'NAMA' as a categorical feature and we can create flags based on OBESITAS, RIW HIPERTENSI, SOSEK RENDAH
df['OBESITAS'] = (df['OBESITAS'] > 0).astype(int)
df['RIW_HIPERTENSI_FLAG'] = (df['RIW HIPERTENSI'] > 0).astype(int)
df['SOSEK_RENDAH_FLAG'] = (df['SOSEK RENDAH'] > 0).astype(int)

# Choose features for encoding
features = ['NAMA', 'OBESITAS', 'RIW_HIPERTENSI_FLAG', 'SOSEK_RENDAH_FLAG']
target = 'USIA'  # You need to have this column in your DataFrame

# If 'HeartDisease' column does not exist, create a sample target variable for demonstration
# For this example, let's assume you have a way to determine 'HeartDisease'
# e.g., a dummy variable, for now, we will create a random binary target
import numpy as np

# Creating a sample target variable
if 'USIA' not in df.columns:
    np.random.seed(0)  # For reproducibility
    df['USIA'] = np.random.choice([0, 1], size=len(df))

# Encoding categorical variables
label_encoder = LabelEncoder()
df['NAMA'] = label_encoder.fit_transform(df['NAMA'])  # Encoding names, if applicable

# Convert 'USIA' to a consistent data type before encoding
# Choose either string or numeric based on your data and analysis needs
# Example: Converting to string
df['USIA'] = df['USIA'].astype(str)

# Now you can encode 'USIA'
df['USIA'] = label_encoder.fit_transform(df['USIA'])

# Display the DataFrame with formatted table
print("Data after encoding:")
print(df[features + [target]].head(10))

# Separate features (X) and target (y)
X = df[features]
y = df[target]

# Print some data from X and y
print("Features (X):")
print(X.head(10))
print("Target (y):")
print(y.head(10))

Data after encoding:
   NAMA  OBESITAS  RIW_HIPERTENSI_FLAG  SOSEK_RENDAH_FLAG  USIA
0     0         0                    0                  0    21
1   111         0                    0                  0    38
2   222         0                    0                  0    12
3   333         0                    0                  0     7
4   444         0                    0                  0    52
5   517         0                    0                  0    35
6   528         0                    0                  0    56
7   539         0                    0                  0    35
8   550         0                    0                  0    63
9     1         0                    0                  0    59
Features (X):
   NAMA  OBESITAS  RIW_HIPERTENSI_FLAG  SOSEK_RENDAH_FLAG
0     0         0                    0                  0
1   111         0                    0                  0
2   222         0                    0                  0
3   333         0            

In [96]:
!pip install scikit-learn #installing the necessary library

# Still Broken

In [97]:


import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # Importing confusion_matrix, accuracy_score, and classification_report

# ... (your existing code) ...

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest Classifier
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred) # Now confusion_matrix is defined
class_report = classification_report(y_test, y_pred) # Now classification_report is defined

# Print evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.07079646017699115
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         1
          16       1.00      0.20      0.33         5
          17       0.00      0.00      0.00         4
          18       0.00      0.00      0.00       

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_